### ISSUE TITLE
Tag {$myJournal_articleId} não funciona

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/ojs#10]
A tag {$myJournal_articleId} não está trazendo o ID da submissão nos e-mails.

Alguns exemplos:
http://submission.scielo.br/index.php/epsic/editor/submissionEmailLog/143017/1433809
http://submission.scielo.br/index.php/epsic/editor/submissionEmailLog/143024/1433837

(tem que entrar como algum editor do periódico para poder visualizar)

**Comment by alexxxmendonca** [comment]
Prezados,
Esse seria o próximo item na lista de prioridades. Como podemos resolvê-lo?

**Comment by beghelli** [comment]
Acho mais fácil adicionar essa variável, com o id real do artigo.

**Comment by beghelli** [comment]
Assim o replace pode ser $articleId por $myJournal_articleId

**Comment by beghelli** [comment]
é só rodar no servidor produtivo:
UPDATE email_templates_data SET subject = REPLACE(subject, '$myJournal_articleId', '$articleId');
UPDATE email_templates_default_data SET subject = REPLACE(subject, '$myJournal_articleId', '$articleId');
UPDATE email_templates_data SET body = REPLACE(body, '$myJournal_articleId', '$articleId');
UPDATE email_templates_default_data SET body = REPLACE(body, '$myJournal_articleId', '$articleId');

Já testei no de testes e foi ok. Se você quiser conferir antes Alex, está lá.

**Comment by alexxxmendonca** [comment]
Bruno,

Algo está estranho -- os templates não estão mais sendo carregados. Quando
clico para enviar um e-mail, aparece apenas a assinatura do usuário, e no
campo "subject" apenas o acrônimo do periódico.

Isso está acontecendo com vários e-mails.

Abs.

*--*
*Alex Mendonça*
*SciELO *
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639 Ramal/Ext. 113*
*www.scielo.org <http://www.scielo.org> | www.scielo.br
<http://www.scielo.br> | blog.scielo.org <http://blog.scielo.org>*

Inscreva-se
<http://scielo.us4.list-manage.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=815cbad617>
na newsletter mensal *SciELO em Perspectiva*: informação e conhecimento
orientado para o desenvolvimento da comunicação científica.

Sign up
<http://scielo.us4.list-manage1.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=cd8ad67f4c>
to
the *SciELO in Perspective* monthly newsletter: information and knowledge
oriented to the development of scientific communication.

**Comment by beghelli** [comment]
Sim Alex, eu acidentalmente deletei os dados de todos os emails no servidor de testes. Eu posso recuperar isso, mas preciso de exportar os dados do servidor produtivo e importar novamente no servidor de testes, e para isso preciso de acesso ao servidor produtivo. Ou pelo menos que vcs exportem as tabelas email_templates, email_templates_data, email_templates_default, email_templates_default_data e me enviem o sql.

**Comment by alexxxmendonca** [comment]
Bruno, já te passei os dados de acesso do sistema de produção, com isso
você consegue resolver esse problema?

*--*
*Alex Mendonça*
*SciELO *
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639 Ramal/Ext. 113*
*www.scielo.org <http://www.scielo.org> | www.scielo.br
<http://www.scielo.br> | blog.scielo.org <http://blog.scielo.org>*

Inscreva-se
<http://scielo.us4.list-manage.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=815cbad617>
na newsletter mensal *SciELO em Perspectiva*: informação e conhecimento
orientado para o desenvolvimento da comunicação científica.

Sign up
<http://scielo.us4.list-manage1.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=cd8ad67f4c>
to
the *SciELO in Perspective* monthly newsletter: information and knowledge
oriented to the development of scientific communication.

2015-02-27 9:26 GMT-03:00 Bruno Beghelli <notifications@github.com>:

**Comment by beghelli** [comment]
não, eu preciso do acesso ao banco de dados produtivo, isso só pessoal da infra pode me passar.

**Comment by alexxxmendonca** [comment]
@jamilatta você pode ver isso que o Bruno solicitou?

**Comment by jamilatta** [comment]
Vou verificar.

**Comment by rondinelisaad** [comment]
Aplicado no BD em produção. Segue resultado da execução:
mysql> UPDATE email_templates_data SET subject = REPLACE(subject, '$myJournal_articleId', '$articleId');
Query OK, 468 rows affected (0.04 sec)
Rows matched: 8627  Changed: 468  Warnings: 0

mysql> UPDATE email_templates_default_data SET subject = REPLACE(subject, '$myJournal_articleId', '$articleId');
Query OK, 1 row affected (0.04 sec)
Rows matched: 759  Changed: 1  Warnings: 0

mysql> UPDATE email_templates_data SET body = REPLACE(body, '$myJournal_articleId', '$articleId');
Query OK, 3644 rows affected (0.05 sec)
Rows matched: 8627  Changed: 3644  Warnings: 0

mysql> UPDATE email_templates_default_data SET body = REPLACE(body, '$myJournal_articleId', '$articleId');
Query OK, 112 rows affected (0.00 sec)
Rows matched: 759  Changed: 112  Warnings: 0
Peço que valide.

**Comment by jamilatta** [comment]
@alexxxmendonca 

reavaliamos a execução e tudo foi executado corretamente, peço para verificar junto ao consultor se existe mais algum passo e/ou reavaliar a solução.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em produção.
