### ISSUE TITLE
Áreas de conhecimento com entidades

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/ojs#11]
Vários usuários estão com "%20" atuando como separador (espaço) das áreas de conhecimento, dentre outras entidades no lugar de caracteres acentuados.

Exemplo:
![image](https://cloud.githubusercontent.com/assets/4059679/5201613/bbf4f912-755b-11e4-9ebc-2939ecef6d5a.png)

Isso acarreta em uma série de problemas na busca de avaliadores usando o critério por área e, mais grave ainda, quando a string que mostra a área é muito grande, ela empurra as outras colunas para o lado direito, impossibilitando o usuário de designar um avaliador.

A solução é diminuir o tamanho da fonte, até que a coluna com o link apareça:

![image](https://cloud.githubusercontent.com/assets/4059679/5201646/1b4ed158-755c-11e4-8376-155df605b8ef.png)

Seria possível corrigir esse problema? Varrendo todos os registros que estão com entidades e substituí-las por seus respectivos caracteres?

**Comment by alexxxmendonca** [comment]
Sim, apenas nessa página.

**Comment by alexxxmendonca** [comment]
Prezados,

Aguardo um retorno sobre esse problema. As revistas continuam com esse problema e recebemos reclamações diariamente.

Como podemos resolvê-lo?

**Comment by jamilatta** [comment]
@alexxxmendonca isso acontecia na versão anterior?

**Comment by beghelli** [comment]
Eu tentei reproduzir isso aqui mas ainda não consegui... eu vou precisar de
acesso ao servidor mysql para ver como estão esses dados no banco.

2015-01-12 9:52 GMT-02:00 Jamil Atta Junior <notifications@github.com>:

**Comment by alexxxmendonca** [comment]
@jamilatta Não.
@beghelli Você não consegue reproduzir os passos? É na escolha dos avaliadores.

**Comment by beghelli** [comment]
O problema é que não tenho os memos dados que o banco de dados de vocês...
acho que por isso não consigo. Vou tentar outra coisa aqui, se não der
certo vou precisar mesmo olhar no servidor de testes da Scielo. Acho que a
revista de testes deve ter o mesmo problema não?

2015-01-12 10:06 GMT-02:00 alexxxmendonca <notifications@github.com>:

**Comment by alexxxmendonca** [comment]
Sim, embora não o suficiente para empurrar o link "DESIGNAR" (as strings não são longas o suficientes). Mas sim, tem o mesmo problema no charset.

**Comment by beghelli** [comment]
Descobri o problema. Por alguma razão a codificação dos dados de interesses
dos usuários está em binário, e não em latin1. Vou tentar corrigir na de
teste primeiro, já já posto o resultado.

2015-01-12 10:11 GMT-02:00 alexxxmendonca <notifications@github.com>:

**Comment by jamilatta** [comment]
Legal

2015-01-12 15:34 GMT-02:00 Bruno Beghelli <notifications@github.com>:

> Descobri o problema. Por alguma razão a codificação dos dados de
> interesses
> dos usuários está em binário, e não em latin1. Vou tentar corrigir na de
> teste primeiro, já já posto o resultado.
>
> 2015-01-12 10:11 GMT-02:00 alexxxmendonca <notifications@github.com>:
>
> > Sim, embora não o suficiente para empurrar o link "DESIGNAR" (as strings
> > não são longas o suficientes). Mas sim, tem o mesmo problema no charset.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scieloorg/ojs/issues/11#issuecomment-69561353>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/ojs/issues/11#issuecomment-69609795>.
>



-- 
Atenciosamente,

Jamil Atta Junior

**Comment by beghelli** [comment]
Ainda estou trabalhando nisso. O problema é mais chato do que eu achava, alguns dados estão com o charset correto, outros não. Ainda não sei como resolver, dou uma notícia assim que tiver uma solução.

**Comment by alexxxmendonca** [comment]
Ok!

*--*
*Alex Mendonça*
*SciELO *
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639 Ramal/Ext. 113*
*www.scielo.org <http://www.scielo.org> | www.scielo.br
<http://www.scielo.br> | blog.scielo.org <http://blog.scielo.org>*

Inscreva-se
<http://scielo.us4.list-manage.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=815cbad617>
na newsletter mensal *SciELO em Perspectiva*: informação e conhecimento
orientado para o desenvolvimento da comunicação científica.

Sign up
<http://scielo.us4.list-manage1.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=cd8ad67f4c>
to
the *SciELO in Perspective* monthly newsletter: information and knowledge
oriented to the development of scientific communication.

2015-01-14 10:15 GMT-02:00 Bruno Beghelli <notifications@github.com>:

**Comment by jamilatta** [comment]
Ciente

2015-01-14 10:17 GMT-02:00 alexxxmendonca <notifications@github.com>:

> Ok!
>
> *--*
> *Alex Mendonça*
> *SciELO *
> *FAPESP - CNPq - BIREME - **FAP UNIFESP*
> *Av. Onze de Junho, 269*
> *04041-050 - São Paulo-SP - Brasil*
> *Tel.: 55-11-5083-3639 Ramal/Ext. 113*
> *www.scielo.org <http://www.scielo.org> | www.scielo.br
> <http://www.scielo.br> | blog.scielo.org <http://blog.scielo.org>*
>
> Inscreva-se
> <
> http://scielo.us4.list-manage.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=815cbad617>
>
> na newsletter mensal *SciELO em Perspectiva*: informação e conhecimento
> orientado para o desenvolvimento da comunicação científica.
>
> Sign up
> <
> http://scielo.us4.list-manage1.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=cd8ad67f4c>
>
> to
> the *SciELO in Perspective* monthly newsletter: information and knowledge
> oriented to the development of scientific communication.
>
> 2015-01-14 10:15 GMT-02:00 Bruno Beghelli <notifications@github.com>:
>
> > Ainda estou trabalhando nisso. O problema é mais chato do que eu achava,
> > alguns dados estão com o charset correto, outros não. Ainda não sei como
> > resolver, dou uma notícia assim que tiver uma solução.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scieloorg/ojs/issues/11#issuecomment-69908080>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/ojs/issues/11#issuecomment-69908266>.
>



-- 
Atenciosamente,

Jamil Atta Junior

**Comment by beghelli** [comment]
Caros, corrigi a maioria das entidades. Alex, pode verificar no sistema de testes. 

Ainda faltam algumas (46, mais precisamente) que teremos que corrigir manualmente, pois o código é o mesmo mas o char certo não. Estou enviando a lista para o Alex. É só corrigir no arquivo txt mesmo Alex, salvar e me enviar que eu faço o resto.

**Comment by alexxxmendonca** [comment]
Arquivo corrigido e enviado ao Bruno.

**Comment by beghelli** [comment]
Alex, você verificou o sistema de testes? Posso enviar o processo de correção para vocês executarem no servidor produtivo?

**Comment by alexxxmendonca** [comment]
Sim, verifiquei e está tudo OK. Pode atualizar a produção.

**Comment by jamilatta** [comment]
@beghelli para executar esse procedimento é necessário uma parada do sistema?

**Comment by beghelli** [comment]
Caros, se formos olhar pelo lado mais seguro, o correto seria parar o
sistema bem rapidinho, fazer o backup, executar este sql, conferir que deu
tudo certo e colocar o sistema online novamente. Esse é o procedimento
padrão né? Não seria necessário do lado técnico, mas eu acho que é o mais
correto do lado da segurança. Não vai ser difícil realizar isso de
madrugada, num horário pouco usado. Eu mesmo posso fazê-lo se vocês me
derem acesso.

Abraços.

Em 2 de fevereiro de 2015 09:46, Jamil Atta Junior <notifications@github.com

**Comment by jamilatta** [comment]
@beghelli vou verificar essa opção com a infra-estrutura.

2015-02-02 9:58 GMT-02:00 Bruno Beghelli <notifications@github.com>:

> Caros, se formos olhar pelo lado mais seguro, o correto seria parar o
> sistema bem rapidinho, fazer o backup, executar este sql, conferir que deu
> tudo certo e colocar o sistema online novamente. Esse é o procedimento
> padrão né? Não seria necessário do lado técnico, mas eu acho que é o mais
> correto do lado da segurança. Não vai ser difícil realizar isso de
> madrugada, num horário pouco usado. Eu mesmo posso fazê-lo se vocês me
> derem acesso.
>
> Abraços.
>
> Em 2 de fevereiro de 2015 09:46, Jamil Atta Junior <
> notifications@github.com
> > escreveu:
>
> > @beghelli <https://github.com/beghelli> para executar esse procedimento
> é
> > necessário uma parada do sistema?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scieloorg/ojs/issues/11#issuecomment-72444018>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/ojs/issues/11#issuecomment-72445392>.
>



-- 
Atenciosamente,

Jamil Atta Junior

**Comment by jamilatta** [comment]
@beghelli me passe as instrução para que eu possa executar essa tarefa.

**Comment by beghelli** [comment]
Enviado.

Em 2 de fevereiro de 2015 10:49, Jamil Atta Junior <notifications@github.com

**Comment by alexxxmendonca** [comment]
Testado e validado em produção. Problema corrigido.
Agradeço a todos os envolvidos.
