### ISSUE TITLE
Logo duplicado (?)

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/ojs#12]
Alguns periódicos estão com uma imagem aparecendo duplicada no logo, mas não da pra ver o conteúdo da imagem, aparece apenas a área da imagem.

Alguns exemplos:

![image](https://cloud.githubusercontent.com/assets/4059679/5217637/4fd0d7f4-762a-11e4-9144-82d81f9d841f.png)
![image](https://cloud.githubusercontent.com/assets/4059679/5217703/1e8eb7a0-762b-11e4-93db-37b703b28c55.png)

Ela também aparece no item 5. Visual -> Logotipo, mas é impossível de excluí-la.

Teria como remover de uma vez por todas essas "imagens fantasmas"?

**Comment by beghelli** [comment]
Corrigi o primeiro, o segundo só através do banco de dados executando este sql:
DELETE FROM journal_settings WHERE setting_name = 'pageHeaderLogoImage' AND journal_id = 58;

Se tiver mais algum, me diga que eu faço o sql.

**Comment by alexxxmendonca** [comment]
Outros com o mesmo problema:

http://submission.scielo.br/index.php/ape/user
http://submission.scielo.br/index.php/es/user
http://submission.scielo.br/index.php/icse/user
http://submission.scielo.br/index.php/mioc/user
http://submission.scielo.br/index.php/ne/user
http://submission.scielo.br/index.php/psoc/user
http://submission.scielo.br/index.php/rbent/user
http://submission.scielo.br/index.php/reeusp/user
http://submission.scielo.br/index.php/rsbf/user

**Comment by rondinelisaad** [comment]
Executado no BD em produção. Segue o resultado:
mysql> DELETE FROM journal_settings WHERE setting_name = 'pageHeaderLogoImage' AND journal_id = 58;
Query OK, 9 rows affected (0.03 sec)
Peço que valide.

**Comment by jamilatta** [comment]
@alexxxmendonca 

reavaliamos a execução e tudo foi executado corretamente, peço para verificar junto ao consultor se existe mais algum passo e/ou reavaliar a solução.

**Comment by alexxxmendonca** [comment]
O problema persiste (os logos continuam duplicados).

**Comment by beghelli** [comment]
Vou dar uma olhada.

**Comment by beghelli** [comment]
Todos estes exemplos que o Alex passou precisam da mesma query, mas o journal id tem que ser substituído pelo id dos mesmo jornais. Ficaria assim:
DELETE FROM journal_settings WHERE setting_name = 'pageHeaderLogoImage' AND journal_id = ?

Com a interrogação sendo substituída pelo journal id de cada um. Dá para pegar a journal id com essa query:

SELECT FROM journals WHERE journal_path = ?

Onde a interrogação é a path do journal, que pode ser obtida olhando a url do jornal, depois de index.php.

**Comment by jamilatta** [comment]
@rondinelisaad 

por gentileza, poderia mandar a lista de IDs para que possa interpolar com o "?" e a partir daí executamos um maço de remoções.

**Comment by beghelli** [comment]
Executei a seguinte query:
DELETE FROM journal_settings WHERE setting_name = 'pageHeaderLogoImage' AND journal_id IN (34, 41, 28, 18, 20, 42, 31, 53, 36, 58);

Removi as settings, verificar se todos os jornais estão ok.

**Comment by alexxxmendonca** [comment]
Testado no ambiente http://homolog.submission.scielo.br/

O problema persiste (os logos "fantasmas" ainda estão lá) e agora sumiu o logo do SciELO também.

**Comment by beghelli** [comment]
ok, verificando.

2015-05-20 11:47 GMT-03:00 alexxxmendonca <notifications@github.com>:

**Comment by beghelli** [comment]
oi Alex... que logo do Scielo que sumiu? Pode verificar os jornais novamente? Não vejo mais a logo fantasma.

**Comment by alexxxmendonca** [comment]
O logo do SciELO está aparecendo agora.

Alguns periódicos persistem com o logo fantasma:

http://submission.scielo.br/index.php/es/user
http://submission.scielo.br/index.php/mioc/user
http://submission.scielo.br/index.php/ne/user
http://submission.scielo.br/index.php/psoc/user
http://submission.scielo.br/index.php/rbent/user
http://submission.scielo.br/index.php/reeusp/user

**Comment by beghelli** [comment]
Alex, vc está olhando o servidor produtivo.

**Comment by alexxxmendonca** [comment]
Não, estou olhando em http://homolog.submission.scielo.br/

As URLs são do ambiente de produção, de fato, mas era só pra você saber o journal path. Desculpe a confusão.

http://homolog.submission.scielo.br/index.php/es/user
http://homolog.submission.scielo.br/index.php/mioc/user
http://homolog.submission.scielo.br/index.php/ne/user
http://homolog.submission.scielo.br/index.php/psoc/user
http://homolog.submission.scielo.br/index.php/rbent/user
http://homolog.submission.scielo.br/index.php/reeusp/user (nesse, o logo que estava antes sumiu e só aparece o fantasma agora)

**Comment by beghelli** [comment]
Talvez limpando o cache do seu browser? Aqui tá tudo sem fantasma :)

**Comment by alexxxmendonca** [comment]
Tem razão! Deve ser cache sim. Tudo certo agora. Somente esse último (http://homolog.submission.scielo.br/index.php/reeusp/user) que o logo que estava antes sumiu, mas isso não é tão grave, eu posso tentar colocar o logo de volta, mas achei estranho.

**Comment by beghelli** [comment]
sim, não era para acontecer, vou tirar essa jornal da lista e colocar a query aqui de novo, segue:

```sql
DELETE FROM journal_settings WHERE setting_name = 'pageHeaderLogoImage' AND journal_id IN (34, 41, 28, 18, 20, 42, 31, 36, 58);
```

**Comment by rondinelisaad** [comment]
Resultado:
mysql> DELETE FROM journal_settings WHERE setting_name = 'pageHeaderLogoImage' AND journal_id IN (34, 41, 28, 18, 20, 42, 31, 36, 58);
Query OK, 60 rows affected (0.11 sec)

Peço que valide.

**Comment by alexxxmendonca** [comment]
O problema persiste em apenas um deles:

http://submission.scielo.br/index.php/reeusp/

Os demais estão OK.

**Comment by rondinelisaad** [comment]
Executado:
mysql> DELETE FROM journal_settings WHERE setting_name = 'pageHeaderLogoImage' AND journal_id IN (53);
Query OK, 3 rows affected (0.00 sec)
Peço que valide.

**Comment by alexxxmendonca** [comment]
O problema persiste:

![image](https://cloud.githubusercontent.com/assets/4059679/7883176/d2520054-05ea-11e5-9b45-47f21546a788.png)

**Comment by beghelli** [comment]
Tem que limpar o cache depois de aplicar o sql gente...

2015-05-29 10:09 GMT-03:00 alexxxmendonca <notifications@github.com>:

**Comment by jamilatta** [comment]
Já limpamos duas vezes.

On Fri, May 29, 2015 at 10:39 AM, Bruno Beghelli <notifications@github.com>
wrote:

> Tem que limpar o cache depois de aplicar o sql gente...
>
> 2015-05-29 10:09 GMT-03:00 alexxxmendonca <notifications@github.com>:
>
> > O problema persiste:
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/4059679/7883176/d2520054-05ea-11e5-9b45-47f21546a788.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scieloorg/ojs/issues/12#issuecomment-106798940>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/ojs/issues/12#issuecomment-106804646>.
>



-- 

Jamil Atta Junior

**Comment by beghelli** [comment]
Limpou o cache do navegador?

2015-05-29 10:43 GMT-03:00 Jamil Atta Junior <notifications@github.com>:

**Comment by alexxxmendonca** [comment]
Testado e aprovado em ambiente de produção.
