### ISSUE TITLE
Estatísticas < 2014 não disponíveis

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/ojs#13]
As estatísticas anteriores ao ano de 2014 não estão disponíveis. 

Na versão anterior, haviam links para mudar o ano, mas nessa versão não tem mais esses links...

É isso mesmo?

**Comment by alexxxmendonca** [comment]
Bruno, alguma novidade sobre isso?

**Comment by beghelli** [comment]
Para limitar o número de anos deste relatório (antes você poderia ir infinitamente para baixo) nós adicionamos uma verificação do ano mais antigo de atividade, mas que usa a data de publicação de artigos e/ou edições para isso. Como a Scielo não publica pelo OJS, essa verificação sempre retorna vazio e então o sistema limita como default o ano corrente, sem dar chance de modificação.

Já criei uma entrada para esse bug https://github.com/pkp/pkp-lib/issues/366 e vou corrigir. Assim que tiver pronto a gente puxa o código para o sistema de produção e resolve isso.

**Comment by alexxxmendonca** [comment]
Bruno,

Ótimo! Obrigado.

O outro problema mais recorrente que estamos tendo é esse:
https://github.com/scieloorg/ojs/issues/14

Abs,

*--*
*Alex Mendonça*
*SciELO *
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639 Ramal/Ext. 113*
*www.scielo.org <http://www.scielo.org> | www.scielo.br
<http://www.scielo.br> | blog.scielo.org <http://blog.scielo.org>*

Inscreva-se
<http://scielo.us4.list-manage.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=815cbad617>
na newsletter mensal *SciELO em Perspectiva*: informação e conhecimento
orientado para o desenvolvimento da comunicação científica.

Sign up
<http://scielo.us4.list-manage1.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=cd8ad67f4c>
to
the *SciELO in Perspective* monthly newsletter: information and knowledge
oriented to the development of scientific communication.

2015-02-27 8:34 GMT-03:00 Bruno Beghelli <notifications@github.com>:

**Comment by beghelli** [comment]
O fix já está disponível há bastante tempo. Desculpe não avisar por aqui, achei que vcs estivessem seguindo o issue. É só aplicar esse patch: https://github.com/pkp/ojs/commit/a9459eb851921827e34402a321ff206422f34a34.diff na produção.

**Comment by alexxxmendonca** [comment]
Caros, aguardo então a aplicação do patch indicado pelo Bruno.

On Tuesday, April 14, 2015, Bruno Beghelli <notifications@github.com> wrote:

> O fix já está disponível há bastante tempo. Desculpe não avisar por aqui,
> achei que vcs estivessem seguindo o issue. É só aplicar esse patch:
> https://github.com/pkp/ojs/commit/a9459eb851921827e34402a321ff206422f34a34.diff
> na produção.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/ojs/issues/13#issuecomment-92936966>.
>


-- 
*--*
*Alex Mendonça*
*SciELO *
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639 Ramal/Ext. 113*
*www.scielo.org <http://www.scielo.org> | www.scielo.br
<http://www.scielo.br> | blog.scielo.org <http://blog.scielo.org>*

Inscreva-se
<http://scielo.us4.list-manage.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=815cbad617>
na newsletter mensal *SciELO em Perspectiva*: informação e conhecimento
orientado para o desenvolvimento da comunicação científica.

Sign up
<http://scielo.us4.list-manage1.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=cd8ad67f4c>
to
the *SciELO in Perspective* monthly newsletter: information and knowledge
oriented to the development of scientific communication.

**Comment by jamilatta** [comment]
@beghelli 

temos o repositório para gerenciar modificações e versões, solicito que seja criado um PR para o nosso branch para que tenhamos essa alteração persistente.

Link: https://github.com/scieloorg/ojs/

**Comment by beghelli** [comment]
Taí: https://github.com/scieloorg/ojs/pull/19

**Comment by jamilatta** [comment]
@rondinelisaad 

podemos realizar essa atualização juntos suspeito que as permissões impeçam também.

**Comment by jamilatta** [comment]
Atualizado em produção por gentileza, verificar.

**Comment by jamilatta** [comment]
Aplicado os últimos commits e obtivemos o seguinte erro, ao acessar (periódico -> Editor Gerente -> Estatisticas & Relatórios): 
![screen shot 2015-05-13 at 10 21 43](https://cloud.githubusercontent.com/assets/373745/7611314/0f214e60-f95a-11e4-9c8c-e954ec1792c7.png)

**Comment by jamilatta** [comment]
Este erro nos obriga a realizarmos um restore de aplicação e base de dados.

**Comment by jamilatta** [comment]
Missão abortada até que esse problema seja resolvido.

**Comment by beghelli** [comment]
Corrigi o método e testado no servidor de homologação. Para passar para a produção, tem que aplicar também esta query no bando de dados:

```sql
UPDATE users SET date_registered = '2005-01-01 00:00:00' WHERE date_registered IS NULL;
```
Por alguma razão o usuário da scielo (que tem relação com todos os jornais e por isso é usado para pegar a atividade mais antiga de um jornal) está com o campo data de registro nulo. Isso faz com que as estatísticas dos anos anteriores também não estejam disponíveis.

Eu setei para o ano da data mais antiga que encontrei de atividades de usuários no banco de dados.

**Comment by alexxxmendonca** [comment]
Testado e aprovado no ambiente http://homolog.submission.scielo.br/

**Comment by alexxxmendonca** [comment]
O problema persiste em ambiente de produção.

**Comment by rondinelisaad** [comment]
Executado:
mysql> UPDATE users SET date_registered = '2005-01-01 00:00:00' WHERE date_registered IS NULL;
Query OK, 1 row affected (0.31 sec)
Rows matched: 1  Changed: 1  Warnings: 0
Peço que valide.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em ambiente de produção.
