### ISSUE TITLE
Plugin "Opções de trabalho do editor de seção"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/ojs#16]
A segunda opção do plugin "Opções de trabalho do editor de seção" não está funcionando.

Testar com o artigo 64496 da Revista Demonstração. Verificar que a autora está enxergando o nome do Editor de Seção (isso não deveria ocorrer).

**Comment by alexxxmendonca** [comment]
Por gentileza, verifique essa pendência. Os periódicos estão sofrendo as consequências desse bug.

**Comment by beghelli** [comment]
Desculpem, não havia visto esta issue. Estou verificando aqui.

**Comment by beghelli** [comment]
Alex, teria como me enviar um link para o artigo?

**Comment by alexxxmendonca** [comment]
Bruno, no exemplo do chamado eu usei esse artigo:
http://submission.scielo.br/index.php/demo/editor/submissionReview/64496

*--*
*Alex Mendonça*
*SciELO *
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639 Ramal/Ext. 113*
*www.scielo.org <http://www.scielo.org> | www.scielo.br
<http://www.scielo.br> | blog.scielo.org <http://blog.scielo.org>*

Inscreva-se
<http://scielo.us4.list-manage.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=815cbad617>
na newsletter mensal *SciELO em Perspectiva*: informação e conhecimento
orientado para o desenvolvimento da comunicação científica.

Sign up
<http://scielo.us4.list-manage1.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=cd8ad67f4c>
to
the *SciELO in Perspective* monthly newsletter: information and knowledge
oriented to the development of scientific communication.

**Comment by beghelli** [comment]
Alex, olhando o código vi que não é um bug. Esta funcionalidade não foi implementada. Não sei o que aconteceu, mas eu e você deixamos isso passar despercebido. Felizmente é uma questão de algumas linhas a mais de código para resolver isso. Assim que eu terminar eu envio um pull request para o repositório da scielo e vcs podem atualizar o sistema.

**Comment by beghelli** [comment]
Alex, conferi e não tem nada de errado com o código mesmo. E sim, a funcionalidade está implementada. O problema deste exemplo é que o editor de seção escolhido não está associado à seção Articles. Então o plugin simplesmente o considera como um editor comum e não trava o contato. 

O plugin só vai travar quando o editor de seção estiver associado à seção do artigo. Você pode acessar agora como o autor daquele artigo de teste e ver que o contato está bloqueado, pois realizei a associação entre editor e seção.

**Comment by alexxxmendonca** [comment]
Bruno, entendo... mas aí temos um problema em potencial. Não gostaríamos
que houvesse essa exigência para o plugin funcionar, explico por que:

Os editores que estiverem associados à uma seção recebem novos artigos
enviados à seção de forma automática, *sem parar na fila de "Não Designado"*.
Isso causa grandes transtornos ao periódico pois os editores passam a
receber os artigos diretamente dos autores, sem passar pela secretaria, e
quase sempre esses artigos vem com erros de formatação e devem voltar para
o autor fazer correções antes de encaminhar aos editores.

Além disso, é comum que o Editor chefe escolha para qual dos editores
associados o artigo será enviado (normalmente a relação é 1 artigo para 1
editor de seção). Se associarmos mais de um editor de seção para uma mesma
seção, todos eles serão designados ao artigo, causando uma grande confusão
pois os editores não saberão quem, de fato, é o real responsável por aquele
artigo.

Pergunto-lhe se seria possível desconsiderar essa camada de condição, uma
vez que no funcionamento original da funcionalidade isso não era exigido e
principalemente pois isso geraria muitos transtornos (mencionados acima).

*--*
*Alex Mendonça*
*SciELO *
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639 Ramal/Ext. 113*
*www.scielo.org <http://www.scielo.org> | www.scielo.br
<http://www.scielo.br> | blog.scielo.org <http://blog.scielo.org>*

Inscreva-se
<http://scielo.us4.list-manage.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=815cbad617>
na newsletter mensal *SciELO em Perspectiva*: informação e conhecimento
orientado para o desenvolvimento da comunicação científica.

Sign up
<http://scielo.us4.list-manage1.com/subscribe?u=f26dcf71797dd37381acb4aa5&id=cd8ad67f4c>
to
the *SciELO in Perspective* monthly newsletter: information and knowledge
oriented to the development of scientific communication.

2015-04-15 8:29 GMT-03:00 Bruno Beghelli <notifications@github.com>:

**Comment by beghelli** [comment]
Sim, vou retirar essa exigência.

Em 15/04/15, alexxxmendonca<notifications@github.com> escreveu:

**Comment by beghelli** [comment]
Oi Alex, retirado. Pode pedir para a infra incorporar esse commit no sistema de testes? Se estiver tudo certo é só atualizar na produção.

**Comment by jamilatta** [comment]
@rondinelisaad 

tentei atualizar a instância, porém não obtive sucesso, por conta de permissões. 

**Rond** podemos realizar essa atualização juntos?

**Comment by rondinelisaad** [comment]
@jamilatta
podemos sim, podemos fazer amanhã se assim desejar.





* Rondineli SaadNetwork Administrator SciELO - Scientific Electronic
Library Online FAPESP - CNPq - BIREME - FapUNIFESP*
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5575-4941
 <http://www.scielo.br>www.scielo.org | www.scielo.br


2015-04-16 15:38 GMT-03:00 Jamil Atta Junior <notifications@github.com>:

**Comment by beghelli** [comment]
Atualizado no sistema de homologação, favor conferir.

**Comment by alexxxmendonca** [comment]
Bruno, apenas o nome do Editor de Seção deve ser oculto. O nome do Editor-Chefe pode aparecer (ou os nomes, quando houver mais de um).

Alterar o label para:

Blinded - Inglês (manter como está)
Oculto - Português
Oculto - Espanhol

**Comment by beghelli** [comment]
Não entendi. Me passa um exemplo?

Em 20 de maio de 2015 15:37, alexxxmendonca <notifications@github.com>
escreveu:

**Comment by alexxxmendonca** [comment]
![untitled-3](https://cloud.githubusercontent.com/assets/4059679/7733596/83fd351c-ff06-11e4-9673-b6bce0311161.png)

Esse artigo possui 2 editores: um "Editor" e um "Editor de Seção". Apenas o usuário com role "Editor de Seção" deve estar oculto.

O autor tem que saber pelo menos o nome do editor-chefe (role "Editor"). Não podemos ocultar completamente todos os editores, senão o autor não sabe com quem entrar em contato quando necessário.

**Comment by beghelli** [comment]
Qual o jornal deste artigo?

Em 20 de maio de 2015 15:41, alexxxmendonca <notifications@github.com>
escreveu:

**Comment by alexxxmendonca** [comment]
demo (journal path)

**Comment by beghelli** [comment]
O dois são editores de seção, por isso ambos estão censurados. O que eu
posso fazer é não censurar se o usuário é um editor de seção mas também um
editor geral, como acontece aqui. Ou melhor, só censurar se o usuário é
apenas um editor de seção e nada mais (editorialmente falando). Pode ser
assim?

2015-05-20 15:48 GMT-03:00 alexxxmendonca <notifications@github.com>:

**Comment by alexxxmendonca** [comment]
"Ou melhor, só censurar se o usuário é apenas um editor de seção e nada mais (editorialmente falando)."

Sim! Isso seria o ideal.

**Comment by beghelli** [comment]
Implementado, esperando confirmação para enviar um pull request.

Em 20 de maio de 2015 16:28, alexxxmendonca <notifications@github.com>
escreveu:

**Comment by alexxxmendonca** [comment]
O comportamento está ok, faltou alterar as labels para:

Blinded - Inglês (manter como está)
Oculto - Português
Oculto - Espanhol

**Comment by beghelli** [comment]
Feito.

Em 21 de maio de 2015 08:42, alexxxmendonca <notifications@github.com>
escreveu:

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.submission.scielo.br/

**Comment by alexxxmendonca** [comment]
Testado e aprovado em ambiente de produção.
